//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Lt {
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class LTResource {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LTResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Lt.LTResource", typeof(LTResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap CASS方格网法计算土方 {
            get {
                object obj = ResourceManager.GetObject("CASS方格网法计算土方", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap ltlogo16 {
            get {
                object obj = ResourceManager.GetObject("ltlogo16", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap ltlogo24 {
            get {
                object obj = ResourceManager.GetObject("ltlogo24", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 云线 {
            get {
                object obj = ResourceManager.GetObject("云线", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 人工硬质场地高程点 {
            get {
                object obj = ResourceManager.GetObject("人工硬质场地高程点", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 倾斜栏杆 {
            get {
                object obj = ResourceManager.GetObject("倾斜栏杆", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 像素法计算土方 {
            get {
                object obj = ResourceManager.GetObject("像素法计算土方", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 函数起坡 {
            get {
                object obj = ResourceManager.GetObject("函数起坡", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 剖面线起坡 {
            get {
                object obj = ResourceManager.GetObject("剖面线起坡", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 单跑楼梯_均匀 {
            get {
                object obj = ResourceManager.GetObject("单跑楼梯_均匀", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 单跑楼梯_定台阶 {
            get {
                object obj = ResourceManager.GetObject("单跑楼梯_定台阶", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 参与计算的设计高程点汇总 {
            get {
                object obj = ResourceManager.GetObject("参与计算的设计高程点汇总", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 双跑楼梯 {
            get {
                object obj = ResourceManager.GetObject("双跑楼梯", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 均匀坡道 {
            get {
                object obj = ResourceManager.GetObject("均匀坡道", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 填挖量可视化 {
            get {
                object obj = ResourceManager.GetObject("填挖量可视化", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 实时山路绘制反馈 {
            get {
                object obj = ResourceManager.GetObject("实时山路绘制反馈", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 小数点位数 {
            get {
                object obj = ResourceManager.GetObject("小数点位数", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 山体坡向分析 {
            get {
                object obj = ResourceManager.GetObject("山体坡向分析", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 山体坡度分析 {
            get {
                object obj = ResourceManager.GetObject("山体坡度分析", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 山体淹没分析 {
            get {
                object obj = ResourceManager.GetObject("山体淹没分析", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 山体高程分析 {
            get {
                object obj = ResourceManager.GetObject("山体高程分析", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 山路坡度分析 {
            get {
                object obj = ResourceManager.GetObject("山路坡度分析", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 平铺嵌板_曲面 {
            get {
                object obj = ResourceManager.GetObject("平铺嵌板_曲面", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 平铺嵌板_网格 {
            get {
                object obj = ResourceManager.GetObject("平铺嵌板_网格", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 延伸至曲线 {
            get {
                object obj = ResourceManager.GetObject("延伸至曲线", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 建立原始高程点 {
            get {
                object obj = ResourceManager.GetObject("建立原始高程点", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 折线成管 {
            get {
                object obj = ResourceManager.GetObject("折线成管", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 折面格栅 {
            get {
                object obj = ResourceManager.GetObject("折面格栅", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 折面框架 {
            get {
                object obj = ResourceManager.GetObject("折面框架", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 曲线台阶 {
            get {
                object obj = ResourceManager.GetObject("曲线台阶", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 曲面偏移实体 {
            get {
                object obj = ResourceManager.GetObject("曲面偏移实体", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 林冠线 {
            get {
                object obj = ResourceManager.GetObject("林冠线", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 格栅框架 {
            get {
                object obj = ResourceManager.GetObject("格栅框架", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 玻璃栏杆02 {
            get {
                object obj = ResourceManager.GetObject("玻璃栏杆02", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 璃栏杆01 {
            get {
                object obj = ResourceManager.GetObject("璃栏杆01", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 等高线淹没分析 {
            get {
                object obj = ResourceManager.GetObject("等高线淹没分析", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 等高线高程分析 {
            get {
                object obj = ResourceManager.GetObject("等高线高程分析", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 简单横向栏杆 {
            get {
                object obj = ResourceManager.GetObject("简单横向栏杆", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 简单玻璃栏杆 {
            get {
                object obj = ResourceManager.GetObject("简单玻璃栏杆", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 简单竖向栏杆 {
            get {
                object obj = ResourceManager.GetObject("简单竖向栏杆", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 精细格栅 {
            get {
                object obj = ResourceManager.GetObject("精细格栅", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 自动山路 {
            get {
                object obj = ResourceManager.GetObject("自动山路", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 自动山路台阶 {
            get {
                object obj = ResourceManager.GetObject("自动山路台阶", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 视线分析 {
            get {
                object obj = ResourceManager.GetObject("视线分析", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 设计自然土地高程点 {
            get {
                object obj = ResourceManager.GetObject("设计自然土地高程点", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 输出__dat格式 {
            get {
                object obj = ResourceManager.GetObject("输出__dat格式", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap 道路边缘均匀取点 {
            get {
                object obj = ResourceManager.GetObject("道路边缘均匀取点", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
